// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNOoJjJ-6WqdBRYkNWaC0_V_1gBDsEknU',
    appId: '1:927927619730:web:e7ff5b7b8291cad329964b',
    messagingSenderId: '927927619730',
    projectId: 'pipo-7550c',
    authDomain: 'pipo-7550c.firebaseapp.com',
    storageBucket: 'pipo-7550c.appspot.com',
    measurementId: 'G-WKPQ4J2P5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUmiLLBqdQQPYBHFjX8QV2NUsp0I5cRRM',
    appId: '1:927927619730:android:799cf42c849e166e29964b',
    messagingSenderId: '927927619730',
    projectId: 'pipo-7550c',
    storageBucket: 'pipo-7550c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8US1vLgCMqxNHYdonqsY1g-B1NbtYNpk',
    appId: '1:927927619730:ios:70ce96acd2ea8d7529964b',
    messagingSenderId: '927927619730',
    projectId: 'pipo-7550c',
    storageBucket: 'pipo-7550c.appspot.com',
    iosBundleId: 'com.example.gameTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8US1vLgCMqxNHYdonqsY1g-B1NbtYNpk',
    appId: '1:927927619730:ios:4d9d8bc59662bc5f29964b',
    messagingSenderId: '927927619730',
    projectId: 'pipo-7550c',
    storageBucket: 'pipo-7550c.appspot.com',
    iosBundleId: 'com.example.gameTemplate.RunnerTests',
  );
}
